import Head from 'next/head'
import generatePDF, {Margin} from 'react-to-pdf';

const personalizacao = {
  method: 'open',
  page: {
    margin: Margin.SMALL,
    format: 'A4',
    orientation: 'portrait',
 },
}

const recuperarConteudoParaPDF = () => document.getElementById('conteudo');

export default function Home() {
  return (
    <>
      <Head>
        <title>PDF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <button onClick={() => generatePDF(recuperarConteudoParaPDF, personalizacao)}>Gerar PDF</button>
      
      <div id="conteudo">
        <h1 style={{textAlign: 'center', color: 'black', fontSize: '25px'}}>
          Ficha Esxicata
        </h1>

        {/* Adicione a tabela abaixo da Ficha Esxicata */}
        <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '20px' }}>
          <thead>
            <th style={{ border: '1px solid black' }}>INSTITUTO FEDERAL DO PIAUI</th>
            <th style={{ border: '1px solid black' }}>CAMPUS TERESINA CENTRAL</th>
          </thead>
        </table>

        <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '20px' }}>
            <tbody>
            <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '12px', textAlign: 'left'}}>FAMILIA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '12px', textAlign: 'left'}}>NOME CIENTIFICO:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '12px' }}>DETERMINADOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '12px', width: '30%' }}>DATA DA DET.:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '12px', textAlign: 'left'}}>NOME VULGAR:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '12px'}}>HÁBITO DE CRESCIMENTO:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '12px'}}>COR DA FLOR, BRACTEA OU ESPORÓFORO:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '12px', textAlign: 'left'}}>AMBIENTE:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '12px', textAlign: 'left'}}>LUGAR DE COLETA:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px'}}></td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '12px' }}>DATA DA COLETA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '12px', textAlign: 'left'}}>COLETOR:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '12px', textAlign: 'left'}}>OBS.:</td>
              </tr>
            </tbody>
          </table>
         </div>
      </main>
    </>
  )
}
