import Head from 'next/head'
import generatePDF, {Margin} from 'react-to-pdf';

const personalizacao = {
  method: 'open',
  page: {
    margin: Margin.SMALL,
    format: 'A4',
    orientation: 'portrait',
 },
}

const tabelaEstilo = {
  border: '1px solid black',
  padding: '8px',
  fontSize: '10px', // Reduza o tamanho da fonte
  lineHeight: '1', // Reduza a altura da linha
};

export default function Home() {
  const cabecalho = (
    <thead>
      <th style={{ border: '1px solid black' }}>INSTITUTO FEDERAL DO PIAUI</th>
      <th style={{ border: '1px solid black' }}>CAMPUS TERESINA CENTRAL</th>
    </thead>
  );

const recuperarConteudoParaPDF = () => document.getElementById('conteudo')
const espacoVazio = <tr><td colSpan="2" style={{ height: '10px' }}></td></tr>;
const espacoVazioTabelas = <tr><td colSpan="2" style={{ height: '50px' }}></td></tr>;

  return (
    <>
      <Head>
        <title>PDF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <button onClick={() => generatePDF(recuperarConteudoParaPDF, personalizacao)}>Gerar PDF</button>
      
      <div id="conteudo">
          <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '10px' }}>
            <tbody>
              <tr>
              <td style={{ width: '50%', verticalAlign: 'top' }}>
                  <table style={{ width: '95%', borderCollapse: 'collapse' }}>
                  {cabecalho}
                  {espacoVazio}
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>FAMILIA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>NOME CIENTIFICO:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px' }}>DETERMINADOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px', width: '30%' }}>DATA DA DET.:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>NOME VULGAR:</td>
              </tr>
              <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>HÁBITO DE CRESCIMENTO:</td>
              </tr>
              <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>COR DA FLOR, BRACTEA OU ESPORÓFORO:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>AMBIENTE:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>LUGAR DE COLETA:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px' }}>COLETOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px', width: '38%' }}>DATA DA COLETA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>OBS.:</td>
              </tr>
                  </table>
                </td>
                <td style={{ width: '50%', verticalAlign: 'top' }}>
                  <table style={{ width: '95%', borderCollapse: 'collapse' }}>
                  {cabecalho}
                  {espacoVazio}
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>FAMILIA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>NOME CIENTIFICO:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px' }}>DETERMINADOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px', width: '30%' }}>DATA DA DET.:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>NOME VULGAR:</td>
              </tr>
              <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>HÁBITO DE CRESCIMENTO:</td>
              </tr>
              <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>COR DA FLOR, BRACTEA OU ESPORÓFORO:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>AMBIENTE:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>LUGAR DE COLETA:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px' }}>COLETOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px', width: '38%' }}>DATA DA COLETA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>OBS.:</td>
              </tr>
                  </table>
                </td>
              </tr>
              {espacoVazioTabelas}
              <tr>
              <td style={{ width: '50%', verticalAlign: 'top' }}>
                  <table style={{ width: '95%', borderCollapse: 'collapse' }}>
                  {cabecalho}
                  {espacoVazio}
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>FAMILIA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>NOME CIENTIFICO:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px' }}>DETERMINADOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px', width: '30%' }}>DATA DA DET.:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>NOME VULGAR:</td>
              </tr>
              <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>HÁBITO DE CRESCIMENTO:</td>
              </tr>
              <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>COR DA FLOR, BRACTEA OU ESPORÓFORO:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>AMBIENTE:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>LUGAR DE COLETA:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px' }}>COLETOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px', width: '38%' }}>DATA DA COLETA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>OBS.:</td>
              </tr>
                  </table>
                </td>
                <td style={{ width: '50%', verticalAlign: 'top' }}>
                  <table style={{ width: '95%', borderCollapse: 'collapse' }}>
                  {cabecalho}
                  {espacoVazio}
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>FAMILIA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>NOME CIENTIFICO:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px' }}>DETERMINADOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px', width: '30%' }}>DATA DA DET.:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>NOME VULGAR:</td>
              </tr>
              <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>HÁBITO DE CRESCIMENTO:</td>
              </tr>
              <tr>
                <td colSpan="2" style={{ border: '1px solid black', padding: '10px', fontSize: '10px', textAlign: 'left'}}>COR DA FLOR, BRACTEA OU ESPORÓFORO:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>AMBIENTE:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>LUGAR DE COLETA:</td>
              </tr>
              <tr>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px' }}>COLETOR:</td>
                <td style={{ border: '1px solid black', padding: '12px', fontSize: '10px', width: '38%' }}>DATA DA COLETA:</td>
              </tr>
              <tr>
              <td colSpan="2" style={{ border: '1px solid black', padding: '12px', fontSize: '10px', textAlign: 'left'}}>OBS.:</td>
              </tr>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
         </div>
      </main>
    </>
  );
  }